# Generated by Django 2.0 on 2019-08-08 15:17

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='博客标题', max_length=50, verbose_name='博客标题')),
                ('read_num', models.IntegerField(default=0, help_text='阅读次数', verbose_name='阅读次数')),
                ('comment_num', models.IntegerField(default=0, help_text='评论次数', verbose_name='评论次数')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='文章', verbose_name='文章')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='发布时间', verbose_name='发布时间')),
                ('img_url', models.ImageField(blank=True, default='', upload_to='blog')),
                ('author', models.ForeignKey(help_text='博客作者', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='博客作者')),
            ],
            options={
                'verbose_name': 'YLZ-博客',
                'verbose_name_plural': 'YLZ-博客',
                'db_table': 'tb_mysite',
                'ordering': ['id', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.CharField(help_text='博客类型', max_length=20, verbose_name='博客类型')),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_type',
            field=models.ForeignKey(help_text='博客类型', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.BlogType', verbose_name='博客类型'),
        ),
    ]
