# Generated by Django 2.0 on 2019-08-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogs_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='text',
            field=models.TextField(default='', help_text='文章摘要', max_length=300, verbose_name='文章摘要'),
        ),
    ]
