# Generated by Django 2.0 on 2020-05-10 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_remove_blogs_comment_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=50, verbose_name='标题')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='发布时间', verbose_name='发布时间')),
                ('read_num', models.IntegerField(default=0, help_text='阅读次数', verbose_name='阅读次数')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('author', models.ForeignKey(help_text='作者', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '留言板',
                'verbose_name_plural': '留言板',
                'db_table': 'tb_message',
                'ordering': ['id', '-created_time'],
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除'),
        ),
        migrations.AddField(
            model_name='blogtype',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除'),
        ),
    ]
